version: 2.1
jobs:
  build_and_test:
    docker:
      - image: cimg/php:8.1.22
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel_db
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
    environment:
      - DB_HOST: 127.0.0.1
      - DB_PASSWORD: root

    steps:
      - checkout
      - run:
          name: composer依存関係をインストール
          command: |
            cd src
            composer install -n --prefer-dist
      - run:
          name: マイグレーションを実行
          command: |
            cd src
            php artisan migrate --env=testing --force
      - run:
          name: テストを実行
          command: |
            cd src
            php artisan test --testsuite Feature

  deploy:
    machine:
      image: circleci/classic:edge
    steps:
        - checkout
        - add_ssh_keys:
        - run: ssh ${USER_NAME}@${HOST_NAME} 'cd http://13.231.156.139/ && git pull'

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
      - deploy
          requires:
            - build_and_test
          filters:
            branches:
              only: main
