version: 2.1

jobs:
  build:
    working_directory: ~/project/src
    docker:
      - image: cimg/php:8.1
      - image: mysql:8.0.26
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_db
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: laravel_pass
        command: --default-authentication-plugin=mysql_native_password

    steps:
      - checkout

      # PHP拡張機能のインストール
      - run:
          name: Install PHP extensions and dependencies
          command: |
            apt update && apt install -y default-mysql-client zlib1g-dev libzip-dev unzip libpng-dev libjpeg-dev
            docker-php-ext-configure gd --with-jpeg
            docker-php-ext-install pdo_mysql zip gd

      - run:
          name: Install Composer
          command: |
            curl -sS https://getcomposer.org/installer | php
            mv composer.phar /usr/local/bin/composer
            composer self-update

      - run:
          name: Install project dependencies
          command: composer install

      - run:
          name: Install Node.js dependencies
          command: npm install

# .envファイルの作成
      - run:
          name: Create .env file
          command: |
            echo "DB_CONNECTION=mysql" >> .env
            echo "DB_HOST=127.0.0.1" >> .env
            echo "DB_PORT=3306" >> .env
            echo "DB_DATABASE=laravel_db" >> .env
            echo "DB_USERNAME=laravel_user" >> .env
            echo "DB_PASSWORD=laravel_pass" >> .env
            ls -l .env
            cat .env

      # マイグレーションとシーディングの実行
      - run:
          name: Run migrations and seeders
          command: |
            composer install
            php artisan migrate --env=testing --seed  --force

      - run:
          name: Generate application key
          command: php artisan key:generate


      # テストの実行
      - run:
          name: Run PHPUnit tests
          command: php artisan test --testsuite Feature

workflows:
  version: 2
  build:
    jobs:
      - build
