version: 2.1

jobs:
  build:
    docker:
      - image: php:8.1-fpm
      - image: mysql:8.0.26
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_db
          MYSQL_USER: laravel_user
          MYSQL_PASSWORD: laravel_pass
    steps:
      - checkout
      - run:
          command: |
                cd src
                composer install
                npm ci
                npm run dev

# .envファイルの作成
      - run:
          name: Create .env file
          command: |
            echo "DB_CONNECTION=mysql" >> src/.env
            echo "DB_HOST=mysql" >> src/.env
            echo "DB_PORT=3306" >> src/.env
            echo "DB_DATABASE=laravel_db" >> src/.env
            echo "DB_USERNAME=laravel_user" >> src/.env
            echo "DB_PASSWORD=laravel_pass" >> src/.env
            ls -l src/.env
            cat src/.env
      # マイグレーションとシーディングの実行
      - run:
          name: Run migrations and seeders
          command: |
            cd src
            php artisan migrate:fresh --seed  --force
      # テストの実行
      - run:
          name: Run PHPUnit tests
          command: |
            cd src
            php artisan test --testsuite Feature
workflows:
  version: 2
  build:
    jobs:
      - build