version: 2.1

jobs:
  build:
    docker:
      - image: php:8.1-fpm
    steps:
      - checkout

      # Docker Compose のセットアップ
      - setup_remote_docker:
          version: 20.10.7

      # Docker Compose プロジェクトの構築と起動
      - run:
          name: Docker Compose up
          command: |
            docker-compose -f docker-compose.yml up -d --build

      # 依存関係のインストール
      - run:
          name: Install dependencies
          command: |
            docker-compose exec php composer install

      # 環境変数ファイルのコピー
      - run:
          name: Copy .env
          command: |
            cp .env.example .env

      # .envファイルの設定更新
      - run:
          name: Update .env for testing
          command: |
            sed -i 's/DB_HOST=127.0.0.1/DB_HOST=mysql/' .env && \
            sed -i 's/DB_DATABASE=laravel/DB_DATABASE=laravel_db/' .env && \
            sed -i 's/DB_USERNAME=root/DB_USERNAME=laravel_user/' .env && \
            sed -i 's/DB_PASSWORD=/DB_PASSWORD=laravel_pass/' .env

      # アプリケーションキーの生成
      - run:
          name: Generate application key
          command: |
            docker-compose exec php php artisan key:generate

      # データベースのセットアップ
      - run:
          name: Wait for MySQL
          command: |
            docker-compose exec php sh -c 'while ! mysqladmin ping -hmysql --silent; do sleep 1; done'
      - run:
          name: Run migrations
          command: |
            docker-compose exec php php artisan migrate --force

      # PHPUnitテストの実行
      - run:
          name: Run tests
          command: |
            docker-compose exec php ./vendor/bin/phpunit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
